In [3]:
import numpy

In [4]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
narray = np.array([1,2,3,4])

In [8]:
print(narray)

[1 2 3 4]


In [10]:
print(narray.size)

4


In [12]:
print(narray.dtype)

int32


In [13]:
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [16]:
array1 = np.arange(5,10)

In [17]:
print(array1)

[5 6 7 8 9]


In [18]:
array3 = np.zeros((4,4), dtype=float)

In [19]:
print(array3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
array4 = np.zeros((4,4), dtype=int)
print(array4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
array5 = np.random.randint(0,10,(3,3))
print(array5)

[[9 9 5]
 [3 0 6]
 [1 8 9]]


In [22]:
array6 = np.random.normal(0,1,(3,3))
print(array6)

[[-0.09183419 -0.15055444 -0.96128341]
 [ 2.5511681  -0.31062272 -0.07791327]
 [-0.44615068 -0.48797915 -0.62640341]]


In [23]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [24]:
import numpy as np
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2.shape)

(2, 2)


In [25]:
print(array2)

[[1 2]
 [3 4]]


In [28]:
import numpy as np
array1 = np.arange(4).reshape(1, 4)
print(array1)
array2 = np.arange(8).reshape(2, 4)
print(array2)
array3 = np.concatenate([array1, array2], axis=0)
print(array3.shape)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [30]:
import numpy as np
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)
print(left.shape)
print(left)
print(right.shape)
print(right)
print(right[1][1])

(2, 2)
[[0 1]
 [4 5]]
(2, 2)
[[2 3]
 [6 7]]
7


In [31]:
import numpy as np
array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)
result_array = array * 10
print(result_array)

[[1 9]
 [2 3]]
[[10 90]
 [20 30]]


In [32]:
import numpy as np
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
print(array2)
array3 = array1 + array2
print(array3)

[0 1]
[[0 2]
 [2 4]]


In [33]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
print(array3)
array4 = np.arange(0, 4).reshape(4, 1)
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [34]:
import numpy as np
# Numpy 원소의 값을 조건에 따라 바꿀 때는 다음과 같이 합니다.
# 반복문을 이용할 때보다 매우 빠르게 동작합니다.
# 대체로 이미지 처리(Image Processing)에서 자주 활용됩니다.
array1 = np.arange(16).reshape(4, 4)
print(array1)
array2 = array1 < 10
print(array2)
array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [35]:
import numpy as np
# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]
